### ISSUE TITLE
Can't access www.soundcomparisons.com

### ISSUE THREAD

**Issue by LauraWae** [lingdb/Sound-Comparisons#293] opened 2016-02-14 20:12 UTC

**Comment by runjak** [comment] 2016-02-15 10:51
I have problems reproducing this issue as both, [www.soundcomparisons.com](http://www.soundcomparisons.com) and [soundcomparisons.com](http://soundcomparisons.com) work for me.
Since I'm at the Jena network right now that could still mean that connection to the outside is somewhat limited. I'll check that to make sure the site is available as usual.

**Comment by runjak** [comment] 2016-02-15 10:58
Ok, so by redirecting my traffic trough a Server in Leipzig I've tested that the website is currently available on the internet. Can you please confirm that the site is still unavailable, and from which network/location this is the case? Maybe trying a different network/location could solve the problem if this is a temporary problem. I don't think I can do much about this, so I'll close the issue for now.

**Closed by runjak** 2016-02-15 10:58 UTC
Labels: Bug, Won't Fix
