### ISSUE TITLE
Two more Malakula languages with wrong lat-longs?

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#332] opened 2016-03-31 20:55 UTC
The colours on the Malakula map are for languages grouped by region, but the ones currently named Maraxus and Tautu (to be updated, of course) are supposedly in the Eastern group yet their dots appear next to languages of the northern group.  Check up?  Perhaps the groupings might be rejigged in any case now that we have exact lat-longs?

**Comment by AvivaShimelman** [comment] 2016-03-31 21:35
Laura,

Are you up working on this right now?  Wait a half hour and I'll write a rather long explanation of why we're getting this result. Fixing it has to be a matter of making some principled choices about what kind of information we want to be representing on SC.

A.

**Comment by PaulHeggarty** [comment] 2016-03-31 21:48
It was me, not Laura.  I assigned Laura to this issue only because I can’t find you in the list of people to assign.  I invited you to join the github team for us a few days ago, but don’t know whether you have done so yet, and wonder whether that might be why I can’t assign to you.
On the actual issue, it really is not so important, so just leave it until you're back in May.  Don’t waste half an hour on a long explanation.  I know part of the story in any case.

**Comment by AvivaShimelman** [comment] 2016-03-31 22:28
The issue is that there are "a lot" of languages, the "bush" languages, in particular (off the top of my head: Novol, Nombotkote, Salang, Angavae, Nasarian, Naati, Tape, Maraxus, Naman, Fifti, Nitita, Tesmbol, as well as a bunch in the south east that I haven't gotten to yet) that are not currently spoken in the place where they were "historically" spoken (keep in mind here that people in Malakula were somewhat nomadic and constant warfare among groups resulted in a lot of relocation, so, when people refer to the "original" place where a language was spoken, what they are. in fact, referring to is just the place where that language was spoken immediately before the last great migration, about 70 years ago, so history here here is hardly "time-deep").  Now, in most cases -- all but Tautu and Maraxus, I think -- that migration did not knock any speaker communities into an altogether different region. Our choice in December (which we are obviously -- and usefully -- reviewing now) about what to do in these cases was to place those languages on the SC map somewhere in the region where they were formerly spoken, i.e., not in the region in which they are currently spoken. BUT: In my SC coding, they get classed in terms of the place where they are currently spoken (on which, read on a bit below). So, again, SC-purposes classification/current location of speaker communities and SC-mapping/"historical" language homeland may not match, and, in two cases, that "miscolors" them (I am inferring from this discussion -- can't load site -- that languages are indicated by color).

Further issues bearing on a decision about what to do with these cases:
Arguing for not using historical place:
The old villages are no longer in existence and getting to them is a couple of days of bush-whacking. I'm trying to get in touch with a researcher from ANU who mapped a bunch of the old "Nazara" (community grounds) in the north, and it's possible that he'll have some of the ones we need, but ... 
that means that I'm really just eye-balling it on Google maps. Not tragic in the case of Maraxus and Tautu for inter-dialectical analysis (there's only one remaining dialect), but a very real issue (in fact, the whole reason I was holding off on turning in the metadata) in the case of Batarxopu, Njav, Tirax, and Letemboi.

So -- it looks like we have to decide between:
1. Making the internal SC classification correspond to "history" (but keep in mind that I won't necessarily be able to get the fine NSEW ordering right)
2. Giving SC contemporary speaker community coordinates 
3. "Over-riding" coloring
4 . ....

A.

**Comment by LauraWae** [comment] 2016-07-20 07:37
We can continue to use #328 when more issues about latlong data for Malakula languages come up. I will close this issue now.

**Closed by LauraWae** 2016-07-20 07:37 UTC
Labels: zData: Malakula
