### ISSUE TITLE
Speaker portrait photo files wrongly named

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#324] opened 2016-03-23 08:40 UTC
on ...\OwnCloud\SndComp\Malakula\x Photo portraits of participants
the files are wrongly named.

***Image filenames
The actual photo image files should be named with the same filename string as for the recording sound files, e.g. Oce_Van_Mal_Int_Sth_Letemboi_Aingelemolesa_Dl, followed by _ and then two digits, then .jpg

e.g. 
Oce_Van_Mal_Int_Sth_Letemboi_Aingelemolesa_Dl_01.jpg

The two digits allow for multiple photos. _01 would normally be the speaker portrait, higher numbers would include photos of the village, perhaps.

***Image size/resolution
It would be good to have images that are not too big, perhaps something in the range of 600-800 pixels, or even 400 or so. That would be best for speed and size, especially given how slow internet connections are in Malakula itself, for anyone wanting to use this feature from the island itself. Files should be reduced to this size before sending to Sound Comparisons.

***Deadline
We'd really like to get this done in time for when Russell is back on 31st March 2016.

**Comment by runjak** [comment] 2016-03-23 12:02
Scaling down the images can easily be done with a script running over them in a bunch.
So this is a thing I imagine I could do easily.

**Comment by LauraWae** [comment] 2016-03-23 19:11
I have renamed Oce_Van_Mal_East_Ctr_Naman_Litzlitz_Dl to Oce_Van_Mal_East_Ctr_Naman_Litzlitz_Dl_01.

**Comment by PaulHeggarty** [comment] 2016-03-24 20:22
Five files in there just now.  Four wrongly named.  What is going on?  _01 is needed.

**Comment by LauraWae** [comment] 2016-03-24 21:31
Hi. Sorry. I was late. Next time is mine.

**Comment by AvivaShimelman** [comment] 2016-03-28 10:39
Currently uploading 41 portraits -- have the right name structure, I believe; I have named them based on extrapolation from the information I have entered into the "for pasting" spreadsheet (done -- waiting for information that will allow me to more accurately assign L and L to 9 villages in the bush) and the file names assigned to other files. Obviously, these are just extrapolations. That is why they are going into the "in waiting" file. *I* will change any that need changing after file names are definitively assigned. The last batch had the name structure they did because I was following the instructions I was given: "What would probably be best is for you to send us (or put on OwnCloud?) the actual photo image files, but renamed.  For the website, best use not the person name, but with the same filename string as we use for the recording sound file in Sound Comparisons, e.g. Oce_Van_Mal_Int_Sth_Letemboi_Aingelemolesa_Dl.jpg"
I know it takes less time to change a name than to throw it back to me to do, but, really, as a general rule, you can throw things back to me (even out to me).
I have added a column to the "for pasting" spreadsheet (obviously deletable): "PORTRAIT AVAILABLE"

**Comment by AvivaShimelman** [comment] 2016-03-28 10:46
With regard to pixel count --
Per Jakob's recommendation, I have not limited resolution --
It's always possible to "go smaller" -- so it might be better not to constrain our options from the get-go.

**Comment by AvivaShimelman** [comment] 2016-03-28 12:58
I've pulled the pictures as by definition not "site-ready" -- I'll upload again as soon as I have definitive recording labels.

**Comment by PaulHeggarty** [comment] 2016-03-29 11:59
In the latest Malakula languages reference sheet (Excel file on OwnCloud) there are now 62 language varieties will full filenames, so perhaps there are photos for some more of them by now?

**Comment by AvivaShimelman** [comment] 2016-03-29 15:17
There are 15 currently uploading (as I've made clear, I have for just about
all of this year's and just about none of lasts' (which accounts, of
course, for the majority of your 62). I'm working with a very slow, very
capricious connection, so don't assume you have them all until you have 15
(i.e., if you don't have 15 but you still want to go ahead and work with
them, of course you can, but do be aware that that will mean opening
everything up at least two times).

On Tue, Mar 29, 2016 at 10:59 PM, Paul Heggarty <notifications@github.com>
wrote:

> In the latest Malakula languages reference sheet (Excel file on OwnCloud)
> there are now 62 language varieties will full filenames, so perhaps there
> are photos for some more of them by now?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/lingdb/Sound-Comparisons/issues/324#issuecomment-202853314>
>



-- 
Aviva Shimelman, PhD

**Comment by AvivaShimelman** [comment] 2016-03-29 15:28
PAUL:

Metadata issues I need an executive decision on. As you know, you are not
working with the latest data sheet. On that sheet, I sub-specify dialects.
So, for example, Oce_Van_Mal_Nth_ESth_UWRA_Wala_Dl, is not just dialect
Wala, but dialect Wala-Petreros (I also have Wala-Preng, Wala-Worprev, and
Wala-Botku).

Your data sheet indicates that the website short name is Wala. Usually,
your short names are generated from dialect names (spaces removed), it
seems. That means, I think, that if I now subspecify dialect names in the
case of some of the files which you already have, their short names will
change, as, presumably, will their overall filenames and I don't know what
else. I can leave dialect names unspecified in the case of those files you
already have names for. The issue just becomes that you would, I think,
want the subspecification to show up on the website.


SO - breakdown:

Do you want me to leave everything such that nothing will change on your
data sheets (but then do you have a way of forcing the site to show a
dialect name that will not be the one listed under "dialect" in the
metadata?)


OR


Should I go ahead and specify dialect in the metadata, presumably changing
Website shortname and overall file name? If so, that would mean that the
names I gave to the portraits would have to change to correspond.


In any case, you've kind of forced my hand with regard to the metadata
sheets. I'll send it along in 15 minutes or so.  Be aware, though, that I
may want to change L and L in a dozen cases -- All, though, are in the
interior, so the issue is historical accuracy, not swimming.

I've listed participant names in the notes section of that sheet. I'll add
them to the reference sheet as well. That may not happen today -- it-s 2:37
in the morning.

PLEASE! If there's anything wrong, do not struggle with it. Just kick it
back to me and I'll take care of it.

On Tue, Mar 29, 2016 at 10:59 PM, Paul Heggarty <notifications@github.com>
wrote:

> In the latest Malakula languages reference sheet (Excel file on OwnCloud)
> there are now 62 language varieties will full filenames, so perhaps there
> are photos for some more of them by now?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/lingdb/Sound-Comparisons/issues/324#issuecomment-202853314>
>



-- 
Aviva Shimelman, PhD

**Comment by PaulHeggarty** [comment] 2016-03-29 16:05
Regarding this from Aviva:

_In any case, you've kind of forced my hand with regard to the metadata sheets. I'll send it along in 15 minutes or so. Be aware, though, that I may want to change L and L in a dozen cases -- All, though, are in the interior, so the issue is historical accuracy, not swimming._

I presume you mean the languages reference sheet on OwnCloud.  Or the 'for pasting' sheet?  No problem updating lat-longs, that's just what we need.

**Comment by PaulHeggarty** [comment] 2016-03-29 16:11
On this:

_Should I go ahead and specify dialect in the metadata, presumably changing Website shortname and overall file name? If so, that would mean that the names I gave to the portraits would have to change to correspond._

The photos need the **Sound Comparisons filename**, not your recording filename.  The Sound Comparisons filenames already include language and dialect, so that should not change.  The only exception to this is a case like 
the one you refer to here:  
_Oce_Van_Mal_Nth_ESth_UWRA_Wala_Dl, is not just dialect Wala, but dialect Wala-Petreros _
I’ll try to sort those cases out too, to standardise things.

The **website shortname** is completely superficial and does not affect anything working.  It can be changed at will, and I will do so to standardise on the format:  language (dialect), i.e. the language name, followed by the dialect name in brackets.

**Comment by PaulHeggarty** [comment] 2016-03-29 16:13
Do not change the Sound Comparisons filename (ending _Dl) in any case.  That is produced programmatically.  Any changes you make will be dropped when I next update.  If these do need to change, as for the multiple Wala dialects, then I have to do that, on the basis of the information you put in the other fields.

**Comment by AvivaShimelman** [comment] 2016-03-29 16:26
No, I meant the for-pasting sheet, but I'm actually updating both now.

On Wed, Mar 30, 2016 at 3:05 AM, Paul Heggarty <notifications@github.com>
wrote:

> Regarding this from Aviva:
>
> *In any case, you've kind of forced my hand with regard to the metadata
> sheets. I'll send it along in 15 minutes or so. Be aware, though, that I
> may want to change L and L in a dozen cases -- All, though, are in the
> interior, so the issue is historical accuracy, not swimming.*
>
> I presume you mean the languages reference sheet on OwnCloud. Or the 'for
> pasting' sheet? No problem updating lat-longs, that's just what we need.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/lingdb/Sound-Comparisons/issues/324#issuecomment-202976671>
>



-- 
Aviva Shimelman, PhD

**Comment by AvivaShimelman** [comment] 2016-03-29 16:27
OK. I'll specify dialects. If that makes any make-work, just throw it back
to me, please.

On Wed, Mar 30, 2016 at 3:11 AM, Paul Heggarty <notifications@github.com>
wrote:

> On this:
>
> *Should I go ahead and specify dialect in the metadata, presumably
> changing Website shortname and overall file name? If so, that would mean
> that the names I gave to the portraits would have to change to correspond.*
>
> The photos need the *Sound Comparisons filename*, not your recording
> filename. The Sound Comparisons filenames already include language and
> dialect, so that should not change. The only exception to this is a case
> like
> the one you refer to here:
>
> _Oce_Van_Mal_Nth_ESth_UWRA_Wala_Dl, is not just dialect Wala, but dialect
> Wala-Petreros _
> I’ll try to sort those cases out too, to standardise things.
>
> The *website shortname* is completely superficial and does not affect
> anything working. It can be changed at will, and I will do so to
> standardise on the format: language (dialect), i.e. the language name,
> followed by the dialect name in brackets.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/lingdb/Sound-Comparisons/issues/324#issuecomment-202978626>
>



-- 
Aviva Shimelman, PhD

**Comment by AvivaShimelman** [comment] 2016-03-29 16:29
OK. The only thing that will change is dialect specification in some cases.
I'll point those out clearly.

On Wed, Mar 30, 2016 at 3:13 AM, Paul Heggarty <notifications@github.com>
wrote:

> Do not change the Sound Comparisons filename (ending _Dl) in any case.
> That is produced programmatically. Any changes you make will be dropped
> when I next update. If these do need to change, as for the multiple Wala
> dialects, then I have to do that, on the basis of the information you put
> in the other fields.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/lingdb/Sound-Comparisons/issues/324#issuecomment-202979657>
>



-- 
Aviva Shimelman, PhD

**Comment by LauraWae** [comment] 2016-07-20 07:40
These topics can be treated in #325 for now. I will close this issue.

**Closed by LauraWae** 2016-07-20 07:40 UTC
Labels: 1st, Time 2: Hour or Two, zData: Malakula
